### PR TITLE
Use StructureBuilder api

### LINKED ISSUE #1: Does not work on latest binary ninja dev build
Loading fails on Version 2.4.3107-dev (2021-11-12 05:12:55):

```
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/__init__.py", line 5, in <module>
    from .bnhelpers import BNHelpers
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/bnhelpers.py", line 7, in <module>
    class BNHelpers(object):
  File "/Users/.../Library/Application Support/Binary Ninja/plugins/delphi_ninja/bnhelpers.py", line 34, in BNHelpers
    def _add_vmt_fields(bv: BinaryView, vmt: DelphiVMT, out_struct: types.Structure) -> bool:
AttributeError: module 'binaryninja.types' has no attribute 'Structure'
Python plugin 'delphi_ninja' could not be loaded
```

### PR DESCRIPTION
**Pull request by fabianfreyer**
Fixes #1.

Not sure about downlards compatibility though.

### CODE REVIEW

**Comment by ImNotAVirus** [comment]
Thanks for the PR!

The StructureBuilder type does not seem to exist in the [latest version](https://api.binary.ninja/binaryninja.types-module.html) of the Binja stable API.

For the backwards compatibility maybe you can do something like : 

```python
try:
    vmt_struct = types.StructureBuilder.create()
except AttributeError:
    vmt_struct = types.Structure()
```

And define an alias for types : 

```python
try:
    StructureType = types.StructureBuilder
except AttributeError:
    StructureType = types.Structure

[...]

def _add_vmt_fields(bv: BinaryView, vmt: DelphiVMT, out_struct: StructureType) -> bool:
    [...]
```

**Review by ImNotAVirus — CHANGES_REQUESTED** [review]
Thanks for the PR!
Can you check my message on the main page of the PR for the backwards compatibility please.
Thanks again.

**Comment by fabianfreyer** [comment]
Yep, haven't tested it so far though.

**Comment by ImNotAVirus** [comment]
I cleaned the master branch to remove dev commits.  
Can you do a PR on the 'main' branch please. I tested your commit and it works.

**Pull request closed without merging**
